name: KillBounty
main: CyberTech\Main
version: 1.0.1.3
api: 1.0.1.3

commands:
    bounty:
        description: "Base Bounty Command"
        promission: Bounty
        useage: "/bounty <set/del/list> [player] [Price]"
permissions:
    Bounty:
        default: true
        description: "Only Bounty Permission"